POST http://127.0.0.1:9000/api/recipes/create
Content-Type: application/json

{
    "name": "FŰSZERES VÉRES HURKA",
    "description": "Cedes és Kovács Áron receptje",
    "steps": [
        "A sütőt 180 fokra előmelegítjük, majd körülbelül 15 perc alatt megsütjük benne a hurkát.",
        "Amíg a hús elkészül, a meghámozott, apró kockákra vágott csicsókát kevés olajon aranybarnára pirítjuk.",
        "Az édesköményt vékony szeletekre vágjuk összeforgatjuk a gyümölcsecettel, majd a mézzel, utána pedig sózzuk, borsozzuk.",
        "Tálaláskor szépen a hurka mellé helyezzük a csicsókát, az édeskömény-salátát, majd egy mustárcsíkkal és egy tükörtojással díszitjük."
    ],
    "createUserId": "1111111111",
    "categoriesIds": "6425cda503c0b17bbc945846",
    "ingredients": [
        "30dkg véreshurka",
        "1dl étolaj",
        "só",
        "bors",
        "2db tojás",
        "5dkg vaj",
        "3db csicsóka",
        "2db kaffir lime levél",
        "1db édeskömény",
        "1dl gyümölcsecet"
    ]
}

###
GET http://127.0.0.1:9000/api/recipes

###
GET http://127.0.0.1:9000/api/recipes/642aaea327a32f54a84f1509

###
GET http://127.0.0.1:9000/api/recipes/search/leves

###
PUT http://127.0.0.1:9000/api/recipes/63f65975656e1e7bf6406723
Content-Type: application/json

{
    "steps": [
        "1",
        "2",
        "3",
        "4",
        "5"
    ]
}

###
DELETE http://127.0.0.1:9000/api/recipes/63f6597e656e1e7bf6406725

###
PUT http://127.0.0.1:9000/api/recipes/63f65983656e1e7bf6406727/like

###
PUT http://127.0.0.1:9000/api/recipes/63f65983656e1e7bf6406727/save

###
POST http://127.0.0.1:9000/api/recipes/63f65983656e1e7bf6406727/comment
Content-Type: application/json

{
    "text": "This is a comment 6",
    "userId": "123"
}

###
DELETE http://127.0.0.1:9000/api/recipes/63f65983656e1e7bf6406727/comment/63f74b3d57ddc7c64843f4ed

###
PUT http://127.0.0.1:9000/api/recipes/63f65983656e1e7bf6406727/category
Content-Type: application/json

{
    "category": ["leves", "gyümölcs"]
}

###
POST http://127.0.0.1:9000/api/users/register
Content-Type: application/json

{
    "username": "teszt10",
    "email": "teszt10@teszt10.com",
    "password": "teszt10"
}

###
POST http://127.0.0.1:9000/api/users/login
Content-Type: application/json

{
    "email": "admin@delicious.com",
    "password": "Passw123"
}

###
GET http://127.0.0.1:9000/api/recipes/category/6425cdb403c0b17bbc945848